(function(){
const STORAGE_KEY='amfeProcesoStd';
let data={header:{organizacion:'',planta:'',fecha:'',responsable:'',cliente:'',confidencialidad:'',modelo:'',equipo:''},processes:[]};
function load(){const saved=localStorage.getItem(STORAGE_KEY);if(saved){try{data=JSON.parse(saved);}catch(e){}}
}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));}
function renderHeader(){const container=document.getElementById('amfeHeader');const inputs=container.querySelectorAll('input');const keys=['organizacion','planta','fecha','responsable','cliente','confidencialidad','modelo','equipo'];inputs.forEach((inp,i)=>{inp.value=data.header[keys[i]]||'';inp.onchange=()=>{data.header[keys[i]]=inp.value;save();};});}
function makeTable(procIdx){const proc=data.processes[procIdx];const table=document.createElement('table');table.className='fmea-table display';const thead=document.createElement('thead');thead.innerHTML='<tr><th>Efecto planta interna</th><th>Efecto planta cliente</th><th>Efecto usuario final</th><th>Causa</th><th>S</th><th>O</th><th>D</th><th>RPN</th><th>Acción preventiva</th><th>Acción detectiva</th><th>Responsable</th><th>Fecha objetivo</th><th>Estado</th><th>Observaciones</th><th></th></tr>';table.appendChild(thead);const tbody=document.createElement('tbody');proc.modos.forEach((m,rIdx)=>{const tr=document.createElement('tr');['efInt','efCli','efUsu','causa','s','o','d','rpn','prev','det','resp','fecha','estado','obs'].forEach((f,idx)=>{const td=document.createElement('td');td.contentEditable=idx!==7;td.textContent=m[f]||'';td.onblur=()=>{const old=m[f]||'';m[f]=td.textContent.trim();if(['s','o','d'].includes(f)){const s=parseInt(m.s)||0,o=parseInt(m.o)||0,d=parseInt(m.d)||0;m.rpn=s*o*d;tr.querySelectorAll('td')[7].textContent=m.rpn;}if(!m.history)m.history=[];if(old!==m[f])m.history.push({field:f,oldValue:old,newValue:m[f],ts:new Date().toISOString()});save();};tr.appendChild(td);});const del=document.createElement('button');del.textContent='🗑';del.onclick=()=>{proc.modos.splice(rIdx,1);save();render();};const tdDel=document.createElement('td');tdDel.appendChild(del);tr.appendChild(tdDel);tbody.appendChild(tr);});table.appendChild(tbody);setTimeout(()=>{$(table).DataTable({paging:false,searching:true,ordering:true,info:false,dom:'Bfrtip',buttons:[{extend:'excelHtml5',title:'AMFE'}]});},0);return table;}
function render(){renderHeader();const container=document.getElementById('processContainer');container.innerHTML='';data.processes.forEach((proc,pIdx)=>{const details=document.createElement('details');details.className='process-section';details.open=true;const summary=document.createElement('summary');summary.textContent=proc.titulo||`Proceso ${pIdx+1}`;details.appendChild(summary);const fields=document.createElement('div');fields.className='process-fields';['estacion','descripcion','materiales','requerimientos'].forEach(key=>{const lab=document.createElement('label');lab.textContent=key.charAt(0).toUpperCase()+key.slice(1);const inp=document.createElement('input');inp.value=proc[key]||'';inp.onchange=()=>{proc[key]=inp.value;save();};lab.appendChild(inp);fields.appendChild(lab);});details.appendChild(fields);const table=makeTable(pIdx);details.appendChild(table);const addBtn=document.createElement('button');addBtn.textContent='+ Modo de Falla';addBtn.className='add-mode-btn';addBtn.onclick=()=>{proc.modos.push({});save();render();};details.appendChild(addBtn);const delProcess=document.createElement('button');delProcess.textContent='Eliminar Proceso';delProcess.className='add-mode-btn';delProcess.onclick=()=>{if(confirm('¿Eliminar proceso?')){data.processes.splice(pIdx,1);save();render();}};details.appendChild(delProcess);container.appendChild(details);});}
window.addEventListener('DOMContentLoaded',()=>{load();render();document.getElementById('addProcess').onclick=()=>{data.processes.push({titulo:'',estacion:'',descripcion:'',materiales:'',requerimientos:'',modos:[]});save();render();};});
})();
