version: '3.8'
services:
  backend:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
      - ./data:/data
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python backend/main.py"
    ports:
      - "8000:8000"
  docs:
    image: nginx:alpine
    volumes:
      - ./docs:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
