version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: barack-backend:latest
    environment:
      - DB_PATH=/data/db.sqlite
    volumes:
      - ./data/db.sqlite:/data/db.sqlite
    ports:
      - "5000:5000"
  docs:
    image: nginx:alpine
    volumes:
      - ./docs:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
