version: '3.8'
services:
  backend:
    build: .
    image: barack-backend:latest
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"
  docs:
    image: nginx:alpine
    volumes:
      - ./docs:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
